-- Seeds adicionales opcionales - Más fotos históricas de Zaragoza
-- Ejecuta este archivo si quieres tener más ejemplos en la base de datos

-- Más fotos históricas con coordenadas reales
INSERT INTO photos (title, description, year, year_from, year_to, era, zone, lat, lng, image_url, thumb_url, source, author, rights, tags) VALUES
(
    'Paseo de Sagasta con tranvías',
    'El Paseo de Sagasta lleno de vida con los tranvías eléctricos circulando. Vista desde la confluencia con Gran Vía.',
    1958,
    NULL,
    NULL,
    'Años 50',
    'Centro',
    41.647500,
    -0.893889,
    '/uploads/paseo-sagasta-1958.jpg',
    '/uploads/thumbs/paseo-sagasta-1958.jpg',
    'Archivo Municipal de Zaragoza',
    'Jalón Ángel',
    'Dominio público',
    ARRAY['Paseo de Sagasta', 'tranvía', 'transporte', 'calle']
),
(
    'Teatro Principal en los años 40',
    'Fachada del Teatro Principal de Zaragoza con público entrando a una función de ópera.',
    1942,
    1940,
    1945,
    'Años 40',
    'Casco Histórico',
    41.654722,
    -0.883056,
    '/uploads/teatro-principal-1942.jpg',
    '/uploads/thumbs/teatro-principal-1942.jpg',
    'Archivo Histórico Provincial',
    'Fotógrafo desconocido',
    'Dominio público',
    ARRAY['Teatro Principal', 'cultura', 'arquitectura', 'ópera']
),
(
    'Mercado de Lanuza',
    'Día de mercado en el antiguo Mercado de Lanuza, demolido posteriormente. Gran afluencia de compradores.',
    1965,
    NULL,
    NULL,
    'Años 60',
    'Centro',
    41.651944,
    -0.878333,
    '/uploads/mercado-lanuza-1965.jpg',
    '/uploads/thumbs/mercado-lanuza-1965.jpg',
    'Colección Coyne',
    'Estudio Coyne',
    'Copyright herederos',
    ARRAY['Mercado de Lanuza', 'comercio', 'vida cotidiana', 'desaparecido']
),
(
    'Antigua Facultad de Medicina',
    'Edificio de la antigua Facultad de Medicina y Ciencias antes de su traslado. Estudiantes en el patio.',
    1970,
    1968,
    1972,
    'Años 70',
    'Universidad',
    41.644444,
    -0.887500,
    '/uploads/facultad-medicina-1970.jpg',
    '/uploads/thumbs/facultad-medicina-1970.jpg',
    'Archivo Universidad de Zaragoza',
    'Servicio Fotográfico UZ',
    'Universidad de Zaragoza',
    ARRAY['Facultad Medicina', 'universidad', 'educación', 'estudiantes']
),
(
    'Plaza de España con fuente',
    'La Plaza de España con su fuente central. Vista panorámica desde el monumento a los Mártires.',
    1955,
    NULL,
    NULL,
    'Años 50',
    'Centro',
    41.653611,
    -0.886944,
    '/uploads/plaza-espana-1955.jpg',
    '/uploads/thumbs/plaza-espana-1955.jpg',
    'Archivo Heraldo de Aragón',
    'Archivo Heraldo',
    'Copyright Heraldo de Aragón',
    ARRAY['Plaza España', 'fuente', 'monumento', 'plaza']
),
(
    'Calle Alfonso I antes de la peatonalización',
    'La céntrica calle Alfonso I con tráfico de vehículos antes de convertirse en calle peatonal.',
    1978,
    1975,
    1980,
    'Años 70',
    'Centro',
    41.652778,
    -0.880556,
    '/uploads/calle-alfonso-1978.jpg',
    '/uploads/thumbs/calle-alfonso-1978.jpg',
    'Archivo Municipal',
    'Departamento Urbanismo',
    'Ayuntamiento de Zaragoza',
    ARRAY['Calle Alfonso', 'urbanismo', 'peatonalización', 'comercio']
),
(
    'Puente de Hierro ferroviario',
    'El antiguo Puente de Hierro del ferrocarril sobre el Ebro. Tren de mercancías cruzando.',
    1932,
    1930,
    1935,
    'Años 30',
    'Delicias',
    41.643056,
    -0.905278,
    '/uploads/puente-hierro-1932.jpg',
    '/uploads/thumbs/puente-hierro-1932.jpg',
    'Renfe Patrimonio Histórico',
    'Archivo Renfe',
    'Renfe',
    ARRAY['Puente de Hierro', 'ferrocarril', 'Ebro', 'transporte']
),
(
    'Arco del Deán',
    'El histórico Arco del Deán que une la Catedral con el Palacio Arzobispal. Vista nocturna.',
    1960,
    NULL,
    NULL,
    'Años 60',
    'Casco Histórico',
    41.655278,
    -0.876389,
    '/uploads/arco-dean-1960.jpg',
    '/uploads/thumbs/arco-dean-1960.jpg',
    'Archivo Catedralicio',
    'Fotógrafo catedralicio',
    'Cabildo Metropolitano',
    ARRAY['Arco del Deán', 'catedral', 'patrimonio', 'noche']
),
(
    'Antigua Audiencia',
    'Edificio de la Antigua Audiencia en la Plaza del Pilar antes de su reforma. Detalle de la fachada renacentista.',
    1945,
    NULL,
    NULL,
    'Años 40',
    'Casco Histórico',
    41.657500,
    -0.879167,
    '/uploads/audiencia-1945.jpg',
    '/uploads/thumbs/audiencia-1945.jpg',
    'Archivo Diputación Provincial',
    'Fotógrafo oficial DPZ',
    'DPZ',
    ARRAY['Audiencia', 'Plaza del Pilar', 'arquitectura', 'renacentista']
),
(
    'Barrio Oliver en construcción',
    'Las primeras viviendas del barrio Oliver durante su construcción. Grúas y obreros trabajando.',
    1972,
    1970,
    1975,
    'Años 70',
    'Oliver',
    41.668333,
    -0.923611,
    '/uploads/barrio-oliver-1972.jpg',
    '/uploads/thumbs/barrio-oliver-1972.jpg',
    'Archivo Municipal - Urbanismo',
    'Servicio municipal',
    'Ayuntamiento de Zaragoza',
    ARRAY['Barrio Oliver', 'construcción', 'urbanismo', 'vivienda']
);

-- Verificar
SELECT COUNT(*) as total_photos FROM photos;
SELECT era, COUNT(*) as count FROM photos GROUP BY era ORDER BY era;
SELECT zone, COUNT(*) as count FROM photos GROUP BY zone ORDER BY zone;
